"""
SOP Templates Module

This module contains templates for generating Standard Operating Procedures
for different types of correlation rules.
"""

from typing import Dict, Any, List
from src.unified_config import config


class SOPTemplates:
    """Collection of SOP templates for different rule types"""
    
    @staticmethod
    def get_default_template() -> str:
        """Get the default SOP template with security analysis"""
        return """# {rule_name} Standard Operating Procedure

## Document Control

| Field | Value |
|-------|-------|
| **Document Type** | Standard Operating Procedure |
| **Classification** | Internal Use Only |
| **Version** | {version} |
| **Last Updated** | {last_reviewed} |
| **Next Review** | {next_review_date} |
| **Author** | {author} |
| **Contact** | {contact_email} |
| **Approved By** | SOC Manager |

---

## Executive Summary

This Standard Operating Procedure (SOP) provides step-by-step guidance for responding to alerts generated by the **{rule_name}** correlation rule. This document is designed for Security Operations Center (SOC) analysts and incident responders to ensure consistent, effective, and timely response to security incidents.

### Quick Reference

| **Alert Type** | {category} |
| **Priority Level** | {priority} |
| **Response Time** | {response_time} |
| **Escalation Threshold** | {escalation_threshold} |

---

## Rule Information

### Basic Details

| **Rule ID** | {rule_id} |
| **Rule Name** | {rule_name} |
| **Status** | {status} |
| **Priority** | {priority} |
| **Category** | {category} |
| **Created Date** | {created_on} |
| **Last Updated** | {last_updated_on} |

### Technical Specifications

| **Search Outcome** | {search_outcome} |
| **Filter Complexity** | {complexity} |
| **Data Sources** | {data_sources} |
| **Event Types** | {event_types} |
| **Confidence Level** | {confidence_level} |

### Search Filter
```
{search_filter}
```

---

## MITRE ATT&CK Framework Mapping

{attack_mapping}

### Tactics and Techniques

| **Tactic** | **Technique** | **Sub-technique** | **Confidence** |
|------------|---------------|-------------------|----------------|
| {tactic_mapping} | {technique_mapping} | {sub_technique_mapping} | {confidence_level} |

---

## Incident Description

### Overview

{description}

### Key Indicators

- **Primary Indicator:** {primary_indicator}
- **Secondary Indicators:** {secondary_indicators}
- **Contextual Information:** {contextual_info}

### Potential Impact

- **Data Impact:** {data_impact}
- **System Impact:** {system_impact}
- **Business Impact:** {business_impact}

---

## Response Procedures

### Phase 1: Initial Triage (0-5 minutes)

#### 1.1 Alert Acknowledgment
- [ ] Acknowledge the alert in the SIEM
- [ ] Document initial timestamp
- [ ] Assign incident number
- [ ] Update incident status to "Under Investigation"

#### 1.2 Initial Assessment
- [ ] Review alert details and context
- [ ] Identify affected systems/users
- [ ] Determine scope and scale
- [ ] Assess potential impact level

#### 1.3 False Positive Check
- [ ] Verify if activity is legitimate
- [ ] Check authorized systems/users
- [ ] Review recent maintenance activities
- [ ] Consult known good activity patterns

### Phase 2: Investigation (5-30 minutes)

#### 2.1 Context Gathering
- [ ] Collect additional system logs
- [ ] Review related security events
- [ ] Check for similar historical patterns
- [ ] Gather network flow data

#### 2.2 Technical Analysis
- [ ] Analyze search filter logic
- [ ] Review data source reliability
- [ ] Check for exclusions/exceptions
- [ ] Verify event correlation

#### 2.3 Root Cause Analysis
- [ ] Identify trigger mechanism
- [ ] Determine underlying vulnerabilities
- [ ] Check configuration issues
- [ ] Document findings

### Phase 3: Response Actions (30-60 minutes)

#### 3.1 Immediate Containment
- [ ] Isolate affected systems (if necessary)
- [ ] Block suspicious network connections
- [ ] Disable compromised accounts
- [ ] Implement network segmentation

#### 3.2 Evidence Collection
- [ ] Preserve all relevant logs
- [ ] Create forensic images (if required)
- [ ] Document all actions taken
- [ ] Collect system snapshots

#### 3.3 Communication
- [ ] Notify relevant stakeholders
- [ ] Update incident management system
- [ ] Prepare initial incident report
- [ ] Coordinate with IT teams

---

## Escalation Matrix

### Immediate Escalation (Within 5 minutes)

**Escalate immediately if any of the following conditions are met:**

- [ ] **Multiple systems affected** (>5 systems)
- [ ] **Critical systems involved** (Domain controllers, financial systems, etc.)
- [ ] **Evidence of data exfiltration** (Large data transfers, suspicious outbound connections)
- [ ] **Suspicious user activity patterns** (Privilege escalation, unusual access patterns)
- [ ] **Known attack patterns detected** (Matches threat intelligence)
- [ ] **High-priority assets compromised** (CEO/executive accounts, sensitive data repositories)

### Escalation to Senior Analyst (Within 15 minutes)

**Escalate to senior analyst if:**

- [ ] **Complex investigation required** (Multiple data sources, advanced analysis needed)
- [ ] **Multiple data sources involved** (SIEM, EDR, network logs, etc.)
- [ ] **Need for additional tools or access** (Forensic tools, specialized access)
- [ ] **Potential false positive but uncertain** (Requires expert judgment)
- [ ] **Business-critical systems affected** (Production systems, customer-facing services)

### Escalation to Incident Response Team (Within 30 minutes)

**Escalate to IRT if:**

- [ ] **Confirmed security incident** (Malware, unauthorized access, data breach)
- [ ] **Multiple attack vectors** (Network, endpoint, application layer)
- [ ] **Advanced persistent threat indicators** (APT patterns, sophisticated techniques)
- [ ] **Regulatory compliance implications** (GDPR, HIPAA, SOX violations)
- [ ] **Public relations concerns** (Customer data, brand impact)

---

## Containment Procedures

### Network Containment

1. **Isolation Steps**
   - Disconnect affected systems from network
   - Implement VLAN isolation
   - Block suspicious IP addresses
   - Restrict access to critical systems

2. **Network Monitoring**
   - Increase monitoring on affected segments
   - Deploy additional sensors
   - Monitor for lateral movement
   - Track network flow patterns

### System Containment

1. **Account Management**
   - Disable suspicious user accounts
   - Reset passwords for affected accounts
   - Review and update access controls
   - Implement additional authentication

2. **System Hardening**
   - Apply security patches
   - Update antivirus signatures
   - Review system configurations
   - Implement additional controls

### Data Protection

1. **Data Isolation**
   - Isolate sensitive data repositories
   - Implement additional encryption
   - Review data access logs
   - Monitor for data exfiltration

---

## Recovery Procedures

### System Recovery (1-4 hours)

1. **System Restoration**
   - Restore systems from clean backups
   - Apply security patches and updates
   - Verify system integrity
   - Test system functionality

2. **Access Management**
   - Re-enable legitimate user accounts
   - Implement additional monitoring
   - Review and update security policies
   - Conduct access reviews

3. **Validation**
   - Test system functionality
   - Verify security controls
   - Monitor for recurrence
   - Document recovery steps

### Business Continuity

1. **Service Restoration**
   - Restore critical business services
   - Verify service availability
   - Monitor service performance
   - Document service status

2. **Communication**
   - Update stakeholders on recovery progress
   - Provide status updates to management
   - Coordinate with business units
   - Prepare recovery report

---

## False Positive Analysis

### Common False Positive Indicators

{false_positive_indicators}

### False Positive Reduction

1. **Tuning Recommendations**
   - Adjust search filter parameters
   - Add exclusion criteria
   - Refine threshold values
   - Update baseline patterns

2. **Validation Procedures**
   - Test rule modifications
   - Validate in test environment
   - Monitor for false positives
   - Document tuning changes

---

## Key Performance Indicators

### Response Metrics

| **Metric** | **Target** | **Measurement** |
|------------|------------|-----------------|
| **Time to Acknowledge** | < 5 minutes | Alert acknowledgment time |
| **Time to Investigate** | < 30 minutes | Investigation completion time |
| **Time to Contain** | < 60 minutes | Containment completion time |
| **Time to Resolve** | < 4 hours | Incident resolution time |

### Quality Metrics

| **Metric** | **Target** | **Measurement** |
|------------|------------|-----------------|
| **False Positive Rate** | < 10% | False positive percentage |
| **Detection Rate** | > 95% | Successful detection rate |
| **Escalation Accuracy** | > 90% | Correct escalation decisions |
| **Documentation Quality** | > 95% | Complete documentation rate |

---

## Lessons Learned

### Process Improvements

- [ ] Document any process improvements
- [ ] Update procedures based on findings
- [ ] Share lessons with the team
- [ ] Update training materials

### Tool Improvements

- [ ] Identify tool limitations
- [ ] Recommend tool enhancements
- [ ] Document tool issues
- [ ] Update tool configurations

### Training Improvements

- [ ] Identify training gaps
- [ ] Update training materials
- [ ] Conduct additional training
- [ ] Share best practices

---

## References and Resources

### Internal Resources

- [Security Incident Response Guide](link-to-internal-guide)
- [Escalation Procedures](link-to-escalation-procedures)
- [Security Best Practices](link-to-best-practices)
- [Tool Documentation](link-to-tool-docs)

### External Resources

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [NIST Cybersecurity Framework](https://www.nist.gov/cyberframework)
- [SANS Incident Response](https://www.sans.org/reading-room/whitepapers/incident/)
- [CIS Controls](https://www.cisecurity.org/controls/)

### Contact Information

| **Role** | **Contact** | **Phone** | **Email** |
|----------|-------------|-----------|-----------|
| **SOC Manager** | {soc_manager} | {soc_manager_phone} | {soc_manager_email} |
| **Senior Analyst** | {senior_analyst} | {senior_analyst_phone} | {senior_analyst_email} |
| **Incident Response Lead** | {ir_lead} | {ir_lead_phone} | {ir_lead_email} |
| **IT Security** | {it_security} | {it_security_phone} | {it_security_email} |

---

## Document History

| **Version** | **Date** | **Author** | **Changes** |
|-------------|----------|------------|-------------|
| {version} | {last_reviewed} | {author} | Initial version |
| 1.1 | {next_review_date} | {author} | Updated procedures |
| 1.2 | {future_date} | {author} | Enhanced escalation matrix |

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
**Classification:** Internal Use Only  

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Containment**
   - Isolate affected systems if necessary
   - Block suspicious network connections
   - Disable compromised accounts if confirmed

2. **Documentation**
   - Document all findings
   - Take screenshots of relevant evidence
   - Update incident tracking system

3. **Communication**
   - Notify relevant stakeholders
   - Update status in incident management system
   - Prepare initial incident report

### Containment Steps (15-60 minutes)

1. **System Isolation**
   - Disconnect affected systems from network
   - Implement network segmentation
   - Restrict access to critical systems

2. **Account Management**
   - Disable suspicious user accounts
   - Reset passwords for affected accounts
   - Review and update access controls

3. **Evidence Preservation**
   - Collect and preserve all relevant logs
   - Create forensic images if necessary
   - Document all actions taken

### Recovery Procedures (1-4 hours)

1. **System Restoration**
   - Restore systems from clean backups
   - Apply security patches and updates
   - Verify system integrity

2. **Access Management**
   - Re-enable legitimate user accounts
   - Implement additional monitoring
   - Review and update security policies

3. **Validation**
   - Test system functionality
   - Verify security controls
   - Monitor for recurrence

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Lessons Learned

- Document any process improvements
- Update procedures based on findings
- Share lessons with the team
- Update training materials if needed

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Security Incident Response Guide](link-to-internal-guide)
- [Escalation Procedures](link-to-escalation-procedures)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_service_account_template() -> str:
        """Specialized template for service account misuse rules"""
        return """# {rule_name} Service Account Misuse Operating Procedure

## Rule Information

**Rule ID:** {rule_id}  
**Status:** {status}  
**Priority:** {priority}  
**Category:** {category}  
**Created:** {created_on}  
**Last Updated:** {last_updated_on}  

## Service Account Context

**Account Name:** {service_account_name}  
**Intended Purpose:** {intended_purpose}  
**Authorized Systems:** {authorized_systems}  
**Access Level:** {access_level}  

## MITRE ATT&CK Mapping

{attack_mapping}

**Confidence Level:** {confidence_level}

## Description

{description}

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}  

### Search Filter
```
{search_filter}
```

## Service Account Analysis

- **Account Status:** {account_status}
- **Last Password Change:** {last_password_change}
- **Group Memberships:** {group_memberships}
- **Scheduled Tasks:** {scheduled_tasks}
- **Normal Usage Patterns:** {normal_usage_patterns}

## Triage Procedure

### Initial Assessment (5 minutes)

1. **Verify Service Account Legitimacy**
   - Check if account exists in authorized service account list
   - Verify account's intended purpose and scope
   - Review account's normal usage patterns
   - Confirm if this is a known legitimate service account

2. **Check for Legitimate Usage**
   - Review recent maintenance activities
   - Check for scheduled tasks or jobs
   - Verify if this is expected behavior
   - Review system maintenance windows

3. **Assess Scope**
   - Determine which systems are affected
   - Identify the type of activity detected
   - Evaluate potential impact on business operations
   - Check for any data access or modification

### Investigation Steps (15-30 minutes)

1. **Service Account Analysis**
   - Review the service account's permissions
   - Check for recent changes to the account
   - Verify the account's intended scope
   - Analyze the specific activities detected

2. **Activity Investigation**
   - Review the specific activities detected
   - Check for patterns in the behavior
   - Identify any unusual access patterns
   - Compare with normal service account usage

3. **System Impact Assessment**
   - Determine which systems were accessed
   - Check for any configuration changes
   - Review for any data access or modification
   - Assess potential lateral movement

### Escalation Criteria

**Immediate Escalation if:**
- Service account used outside intended scope
- Multiple systems accessed unexpectedly
- Evidence of privilege escalation
- Suspicious activity patterns
- Unusual data access or modification

**Escalate to Senior Analyst if:**
- Complex service account relationships
- Need for detailed system analysis
- Potential security policy violations
- Multiple service accounts involved

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Account Containment**
   - Disable the service account if suspicious
   - Monitor for additional activity
   - Document all findings

2. **System Monitoring**
   - Increase monitoring on affected systems
   - Check for additional unauthorized access
   - Review system logs for related activity

3. **Communication**
   - Notify system administrators
   - Alert relevant business units
   - Update incident tracking system

### Containment Steps (15-60 minutes)

1. **Account Management**
   - Reset service account password
   - Review and update account permissions
   - Implement additional monitoring

2. **System Security**
   - Review affected system security
   - Check for any unauthorized changes
   - Implement additional controls

3. **Evidence Collection**
   - Collect all relevant logs
   - Document account activity
   - Preserve system state

### Recovery Procedures (1-4 hours)

1. **Account Restoration**
   - Re-enable legitimate service accounts
   - Update account configurations
   - Implement additional monitoring

2. **System Validation**
   - Verify system functionality
   - Check for any residual issues
   - Update security controls

3. **Process Improvement**
   - Review service account management
   - Update monitoring procedures
   - Implement additional controls

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Service Account Best Practices

- Maintain an up-to-date inventory of service accounts
- Implement least privilege access
- Regular password rotation
- Monitor for unusual activity patterns
- Document intended usage for each account

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Service Account Security Guide](link-to-internal-guide)
- [Privileged Access Management](link-to-pam-guide)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_privilege_escalation_template() -> str:
        """Specialized template for privilege escalation rules"""
        return """# {rule_name} Privilege Escalation Operating Procedure

## Rule Information

**Rule ID:** {rule_id}  
**Status:** {status}  
**Priority:** {priority}  
**Category:** {category}  
**Created:** {created_on}  
**Last Updated:** {last_updated_on}  

## Privilege Escalation Analysis

**Original Privileges:** {original_privileges}  
**Escalated Privileges:** {escalated_privileges}  
**Escalation Method:** {escalation_method}  
**Target Systems:** {target_systems}  

## MITRE ATT&CK Mapping

{attack_mapping}

**Confidence Level:** {confidence_level}

## Description

{description}

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}  

### Search Filter
```
{search_filter}
```

## Triage Procedure

### Initial Assessment (5 minutes)

1. **Identify Escalation Method**
   - Review how privileges were elevated
   - Check for use of known escalation techniques
   - Verify if escalation was authorized
   - Determine the scope of privilege changes

2. **Assess Impact Scope**
   - Determine what systems were accessed
   - Check for lateral movement attempts
   - Review any data accessed with elevated privileges
   - Identify critical systems at risk

3. **Verify Authorization**
   - Check if escalation was legitimate
   - Review administrative activities
   - Verify if this was planned maintenance
   - Assess business impact

### Investigation Steps (15-30 minutes)

1. **Escalation Analysis**
   - Review the specific escalation method used
   - Check for use of known attack techniques
   - Analyze the privilege change details
   - Identify any suspicious patterns

2. **Scope Assessment**
   - Determine which systems were affected
   - Check for lateral movement attempts
   - Review any data accessed or modified
   - Assess potential data exposure

3. **Containment Actions**
   - Immediately revoke elevated privileges
   - Isolate affected systems
   - Monitor for additional escalation attempts
   - Implement additional controls

### Escalation Criteria

**Immediate Escalation if:**
- Unauthorized privilege escalation detected
- Multiple systems affected
- Evidence of lateral movement
- Critical systems compromised
- Known attack patterns detected

**Escalate to Senior Analyst if:**
- Complex escalation scenarios
- Multiple privilege changes involved
- Need for detailed system analysis
- Potential data breach

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Privilege Containment**
   - Immediately revoke elevated privileges
   - Disable compromised accounts
   - Block suspicious network connections

2. **System Isolation**
   - Isolate affected systems
   - Implement network segmentation
   - Restrict access to critical systems

3. **Evidence Collection**
   - Document all privilege changes
   - Collect system logs
   - Preserve forensic evidence

### Containment Steps (15-60 minutes)

1. **Account Management**
   - Reset passwords for affected accounts
   - Review and update access controls
   - Implement additional monitoring

2. **System Security**
   - Review system security configurations
   - Check for unauthorized changes
   - Implement additional controls

3. **Network Security**
   - Review network access controls
   - Check for lateral movement
   - Implement additional monitoring

### Recovery Procedures (1-4 hours)

1. **System Restoration**
   - Restore systems from clean backups
   - Apply security patches and updates
   - Verify system integrity

2. **Access Management**
   - Re-enable legitimate user accounts
   - Implement additional monitoring
   - Review and update security policies

3. **Validation**
   - Test system functionality
   - Verify security controls
   - Monitor for recurrence

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Privilege Escalation Prevention

- Implement least privilege access
- Regular privilege reviews
- Monitor for unusual privilege changes
- Implement just-in-time access
- Regular security awareness training

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Privilege Escalation Guide](link-to-internal-guide)
- [Access Control Best Practices](link-to-access-guide)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_configuration_change_template() -> str:
        """Specialized template for configuration change rules"""
        return """# {rule_name} Configuration Change Operating Procedure

## Rule Information

**Rule ID:** {rule_id}  
**Status:** {status}  
**Priority:** {priority}  
**Category:** {category}  
**Created:** {created_on}  
**Last Updated:** {last_updated_on}  

## Configuration Change Analysis

**Change Type:** {change_type}  
**Changed Component:** {changed_component}  
**Change Method:** {change_method}  
**Affected Systems:** {affected_systems}  

## MITRE ATT&CK Mapping

{attack_mapping}

**Confidence Level:** {confidence_level}

## Description

{description}

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}  

### Search Filter
```
{search_filter}
```

## Triage Procedure

### Initial Assessment (5 minutes)

1. **Verify Change Authorization**
   - Check if change was authorized
   - Review change management procedures
   - Verify if this was planned maintenance
   - Assess business impact

2. **Identify Change Scope**
   - Determine what was changed
   - Check for unauthorized modifications
   - Review change details
   - Assess potential security impact

3. **Check for Legitimate Changes**
   - Review maintenance schedules
   - Check for planned updates
   - Verify if change was expected
   - Assess if change follows procedures

### Investigation Steps (15-30 minutes)

1. **Change Analysis**
   - Review the specific changes made
   - Check for unauthorized modifications
   - Analyze change patterns
   - Identify any suspicious activity

2. **Impact Assessment**
   - Determine systems affected
   - Check for security implications
   - Review for data exposure
   - Assess potential vulnerabilities

3. **Validation Actions**
   - Verify change documentation
   - Check for proper approvals
   - Review change procedures
   - Assess compliance impact

### Escalation Criteria

**Immediate Escalation if:**
- Unauthorized configuration changes
- Critical systems affected
- Security settings modified
- Evidence of malicious activity
- Compliance violations

**Escalate to Senior Analyst if:**
- Complex configuration changes
- Multiple systems affected
- Need for detailed analysis
- Potential security impact

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Change Documentation**
   - Document all changes made
   - Review change approvals
   - Check for proper procedures

2. **Impact Assessment**
   - Determine scope of changes
   - Check for security implications
   - Assess business impact

3. **Communication**
   - Notify relevant stakeholders
   - Update change management system
   - Alert security team if needed

### Containment Steps (15-60 minutes)

1. **Change Validation**
   - Verify change documentation
   - Check for proper approvals
   - Review change procedures

2. **Security Review**
   - Check for security implications
   - Review access controls
   - Assess compliance impact

3. **Process Improvement**
   - Review change procedures
   - Update monitoring
   - Implement additional controls

### Recovery Procedures (1-4 hours)

1. **Change Rollback**
   - Rollback unauthorized changes
   - Restore previous configurations
   - Verify system functionality

2. **Process Updates**
   - Update change procedures
   - Implement additional controls
   - Review monitoring

3. **Validation**
   - Test system functionality
   - Verify security controls
   - Monitor for recurrence

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Configuration Change Best Practices

- Implement change management procedures
- Require proper approvals
- Document all changes
- Monitor for unauthorized changes
- Regular security reviews

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Change Management Guide](link-to-internal-guide)
- [Configuration Security](link-to-config-guide)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_data_exfiltration_template() -> str:
        """Specialized template for data exfiltration rules"""
        return """# {rule_name} Data Exfiltration Operating Procedure

## Rule Information

**Rule ID:** {rule_id}  
**Status:** {status}  
**Priority:** {priority}  
**Category:** {category}  
**Created:** {created_on}  
**Last Updated:** {last_updated_on}  

## Data Exfiltration Analysis

**Data Type:** {data_type}  
**Exfiltration Method:** {exfiltration_method}  
**Destination:** {destination}  
**Data Volume:** {data_volume}  

## MITRE ATT&CK Mapping

{attack_mapping}

**Confidence Level:** {confidence_level}

## Description

{description}

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}  

### Search Filter
```
{search_filter}
```

## Triage Procedure

### Initial Assessment (5 minutes)

1. **Verify Data Movement**
   - Check if data movement was authorized
   - Review data transfer procedures
   - Verify if this was legitimate activity
   - Assess data sensitivity

2. **Identify Data Scope**
   - Determine what data was moved
   - Check for sensitive information
   - Review data classification
   - Assess potential impact

3. **Check for Legitimate Transfers**
   - Review backup procedures
   - Check for authorized transfers
   - Verify if transfer was expected
   - Assess business need

### Investigation Steps (15-30 minutes)

1. **Data Analysis**
   - Review the specific data moved
   - Check for sensitive information
   - Analyze transfer patterns
   - Identify any suspicious activity

2. **Method Investigation**
   - Review how data was transferred
   - Check for unauthorized methods
   - Analyze transfer details
   - Identify potential vulnerabilities

3. **Impact Assessment**
   - Determine data sensitivity
   - Check for data exposure
   - Review compliance implications
   - Assess business impact

### Escalation Criteria

**Immediate Escalation if:**
- Unauthorized data transfer
- Sensitive data involved
- Large data volumes
- Suspicious destination
- Compliance violations

**Escalate to Senior Analyst if:**
- Complex data transfer scenarios
- Multiple data types involved
- Need for detailed analysis
- Potential data breach

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Data Containment**
   - Stop unauthorized transfers
   - Block suspicious destinations
   - Monitor for additional activity

2. **Evidence Collection**
   - Document all transfers
   - Collect transfer logs
   - Preserve evidence

3. **Communication**
   - Notify data protection team
   - Alert legal/compliance
   - Update incident tracking

### Containment Steps (15-60 minutes)

1. **Transfer Analysis**
   - Review all recent transfers
   - Check for additional activity
   - Analyze transfer patterns

2. **Data Protection**
   - Implement additional monitoring
   - Review data access controls
   - Check for data exposure

3. **Process Improvement**
   - Review transfer procedures
   - Update monitoring
   - Implement additional controls

### Recovery Procedures (1-4 hours)

1. **Data Recovery**
   - Attempt data recovery if possible
   - Review backup procedures
   - Check for data availability

2. **Process Updates**
   - Update transfer procedures
   - Implement additional controls
   - Review monitoring

3. **Validation**
   - Verify data integrity
   - Check security controls
   - Monitor for recurrence

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Data Protection Best Practices

- Implement data classification
- Monitor data transfers
- Use encryption for sensitive data
- Regular access reviews
- Data loss prevention tools

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Data Protection Guide](link-to-internal-guide)
- [Data Loss Prevention](link-to-dlp-guide)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_network_anomaly_template() -> str:
        """Specialized template for network anomaly rules"""
        return """# {rule_name} Network Anomaly Operating Procedure

## Rule Information

**Rule ID:** {rule_id}  
**Status:** {status}  
**Priority:** {priority}  
**Category:** {category}  
**Created:** {created_on}  
**Last Updated:** {last_updated_on}  

## Network Anomaly Analysis

**Anomaly Type:** {anomaly_type}  
**Source IP:** {source_ip}  
**Destination IP:** {destination_ip}  
**Protocol:** {protocol}  
**Port:** {port}  

## MITRE ATT&CK Mapping

{attack_mapping}

**Confidence Level:** {confidence_level}

## Description

{description}

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}  

### Search Filter
```
{search_filter}
```

## Triage Procedure

### Initial Assessment (5 minutes)

1. **Verify Network Activity**
   - Check if activity was authorized
   - Review network policies
   - Verify if this was legitimate traffic
   - Assess network impact

2. **Identify Anomaly Scope**
   - Determine affected systems
   - Check for unusual patterns
   - Review network logs
   - Assess potential impact

3. **Check for Legitimate Traffic**
   - Review network maintenance
   - Check for authorized connections
   - Verify if traffic was expected
   - Assess business need

### Investigation Steps (15-30 minutes)

1. **Traffic Analysis**
   - Review the specific network activity
   - Check for unusual patterns
   - Analyze traffic details
   - Identify any suspicious activity

2. **Source Investigation**
   - Review source system activity
   - Check for unauthorized access
   - Analyze connection patterns
   - Identify potential threats

3. **Impact Assessment**
   - Determine systems affected
   - Check for data exposure
   - Review network security
   - Assess business impact

### Escalation Criteria

**Immediate Escalation if:**
- Unauthorized network access
- Suspicious traffic patterns
- Multiple systems affected
- Evidence of attack
- Critical systems involved

**Escalate to Senior Analyst if:**
- Complex network scenarios
- Multiple connections involved
- Need for detailed analysis
- Potential network breach

## Response Actions

### Immediate Actions (0-15 minutes)

1. **Network Containment**
   - Block suspicious connections
   - Isolate affected systems
   - Monitor for additional activity

2. **Traffic Analysis**
   - Review network logs
   - Analyze traffic patterns
   - Document findings

3. **Communication**
   - Notify network team
   - Alert security team
   - Update incident tracking

### Containment Steps (15-60 minutes)

1. **Network Security**
   - Review network security
   - Check for vulnerabilities
   - Implement additional controls

2. **System Analysis**
   - Review affected systems
   - Check for compromise
   - Analyze system logs

3. **Process Improvement**
   - Review network procedures
   - Update monitoring
   - Implement additional controls

### Recovery Procedures (1-4 hours)

1. **Network Restoration**
   - Restore network connectivity
   - Apply security updates
   - Verify network security

2. **System Validation**
   - Verify system functionality
   - Check security controls
   - Monitor for recurrence

3. **Process Updates**
   - Update network procedures
   - Implement additional controls
   - Review monitoring

## False Positive Indicators

{false_positive_indicators}

## Key Indicators to Monitor

{key_indicators}

## Network Security Best Practices

- Implement network segmentation
- Monitor network traffic
- Use intrusion detection
- Regular security reviews
- Network access controls

## References

- [MITRE ATT&CK Framework](https://attack.mitre.org/)
- [Network Security Guide](link-to-internal-guide)
- [Network Monitoring](link-to-monitoring-guide)
- [Security Best Practices](link-to-best-practices)

---

**Generated on:** {generated_date}  
**SOP Version:** {version}  
**Last Reviewed:** {last_reviewed}  
**Author:** {author}  
**Contact:** {contact_email}  
"""

    @staticmethod
    def get_multi_rule_template() -> str:
        """Get template for multiple rules in a single document"""
        return """# {category_title} Standard Operating Procedures

## Overview

This document contains Standard Operating Procedures for {rule_count} {category} rules.

**Generated:** {generated_date}  
**Author:** {author}  
**Contact:** {contact_email}  
**Version:** {version}

## Rule Summary

{rule_summary_table}

## Individual Procedures

{rules_content}

## Category Analysis

### Common Patterns
{common_patterns}

### Shared Indicators
{shared_indicators}

### Escalation Matrix
{escalation_matrix}

## References

- MITRE ATT&CK Framework
- CrowdStrike Documentation
- Internal Security Policies

---

**Generated:** {generated_date}  
**Version:** {version}  
**Author:** {author}  
**Contact:** {contact_email}"""

    @staticmethod
    def get_html_template() -> str:
        """Get enhanced HTML template with modern styling"""
        return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{rule_name} Operating Procedure</title>
    <style>
        body {{ 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            margin: 0; 
            padding: 20px; 
            background: #f5f5f5; 
            color: #333;
        }}
        .container {{ 
            max-width: 1200px; 
            margin: 0 auto; 
            background: white; 
            padding: 30px; 
            border-radius: 8px; 
            box-shadow: 0 2px 10px rgba(0,0,0,0.1); 
        }}
        h1 {{ 
            color: #2c3e50; 
            border-bottom: 3px solid #3498db; 
            padding-bottom: 10px; 
            font-size: 28px;
            margin-top: 0;
        }}
        h2 {{ 
            color: #34495e; 
            margin-top: 30px; 
            border-left: 4px solid #3498db; 
            padding-left: 15px; 
            font-size: 22px;
        }}
        h3 {{ 
            color: #2c3e50; 
            margin-top: 25px; 
            font-size: 18px;
        }}
        .header {{ 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            color: white; 
            padding: 25px; 
            border-radius: 8px; 
            margin-bottom: 30px; 
        }}
        .header h1 {{
            color: white;
            border-bottom: none;
            margin: 0;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .mitre-section {{ 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            color: white; 
            padding: 20px; 
            border-radius: 8px; 
            margin: 20px 0; 
        }}
        .technical-details {{ 
            background: #ecf0f1; 
            padding: 20px; 
            border-radius: 8px; 
            margin: 20px 0; 
            border-left: 4px solid #e74c3c; 
        }}
        .escalation-criteria {{ 
            background: #fff3cd; 
            border: 1px solid #ffeaa7; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        .response-actions {{ 
            background: #d1ecf1; 
            border: 1px solid #bee5eb; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        .section {{ 
            margin: 25px 0; 
            padding: 20px; 
            background: #f8f9fa; 
            border-radius: 8px; 
            border-left: 4px solid #3498db; 
        }}
        .code-block {{ 
            background: #2c3e50; 
            color: #ecf0f1; 
            padding: 15px; 
            border-radius: 5px; 
            font-family: 'Courier New', monospace; 
            overflow-x: auto; 
            margin: 15px 0;
            border-left: 4px solid #e74c3c;
        }}
        .alert {{ 
            background: #f8d7da; 
            border: 1px solid #f5c6cb; 
            color: #721c24; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        .info {{ 
            background: #d1ecf1; 
            border: 1px solid #bee5eb; 
            color: #0c5460; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        .success {{ 
            background: #d4edda; 
            border: 1px solid #c3e6cb; 
            color: #155724; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        .warning {{ 
            background: #fff3cd; 
            border: 1px solid #ffeaa7; 
            color: #856404; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 15px 0; 
        }}
        table {{ 
            border-collapse: collapse; 
            width: 100%; 
            margin: 15px 0; 
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
        th, td {{ 
            border: 1px solid #bdc3c7; 
            padding: 12px; 
            text-align: left; 
        }}
        th {{ 
            background: linear-gradient(135deg, #3498db, #2980b9); 
            color: white; 
            font-weight: bold; 
        }}
        tr:nth-child(even) {{ 
            background-color: #f8f9fa; 
        }}
        tr:hover {{
            background-color: #e3f2fd;
        }}
        .priority-high {{ 
            color: #e74c3c; 
            font-weight: bold; 
        }}
        .priority-medium {{ 
            color: #f39c12; 
            font-weight: bold; 
        }}
        .priority-low {{ 
            color: #27ae60; 
            font-weight: bold; 
        }}
        .confidence-high {{ 
            color: #27ae60; 
            font-weight: bold; 
        }}
        .confidence-medium {{ 
            color: #f39c12; 
            font-weight: bold; 
        }}
        .confidence-low {{ 
            color: #e74c3c; 
            font-weight: bold; 
        }}
        .rule-info-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .rule-info-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #3498db;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
        .rule-info-card h3 {{
            margin-top: 0;
            color: #2c3e50;
        }}
        .step-list {{
            counter-reset: step-counter;
            list-style: none;
            padding: 0;
        }}
        .step-list li {{
            counter-increment: step-counter;
            margin: 15px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 5px;
            border-left: 4px solid #3498db;
        }}
        .step-list li::before {{
            content: counter(step-counter);
            background: #3498db;
            color: white;
            border-radius: 50%;
            width: 25px;
            height: 25px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-right: 10px;
            font-weight: bold;
        }}
        .contact-info {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-top: 30px;
        }}
        .contact-info h3 {{
            color: white;
            margin-top: 0;
        }}
        @media (max-width: 768px) {{
            .container {{
                padding: 15px;
                margin: 10px;
            }}
            .rule-info-grid {{
                grid-template-columns: 1fr;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
    <div class="header">
        <h1>{rule_name} Operating Procedure</h1>
        <p><strong>Generated:</strong> {generated_date} | <strong>Author:</strong> {author} | <strong>Contact:</strong> {contact_email}</p>
    </div>

    <div class="section">
        <h2>Rule Information</h2>
            <div class="rule-info-grid">
                <div class="rule-info-card">
                    <h3>Basic Information</h3>
        <table>
            <tr><td><strong>Rule ID:</strong></td><td>{rule_id}</td></tr>
            <tr><td><strong>Status:</strong></td><td>{status}</td></tr>
            <tr><td><strong>Priority:</strong></td><td class="priority-{priority}">{priority}</td></tr>
            <tr><td><strong>Category:</strong></td><td>{category}</td></tr>
                    </table>
                </div>
                <div class="rule-info-card">
                    <h3>Timeline</h3>
                    <table>
            <tr><td><strong>Created:</strong></td><td>{created_on}</td></tr>
            <tr><td><strong>Last Updated:</strong></td><td>{last_updated_on}</td></tr>
                        <tr><td><strong>Last Reviewed:</strong></td><td>{last_reviewed}</td></tr>
                        <tr><td><strong>Version:</strong></td><td>{version}</td></tr>
        </table>
                </div>
            </div>
    </div>

        <div class="mitre-section">
        <h2>MITRE ATT&CK Mapping</h2>
        {attack_mapping_html}
    </div>

    <div class="section">
        <h2>Description</h2>
        <p>{description}</p>
    </div>

        <div class="technical-details">
        <h2>Technical Details</h2>
            <div class="rule-info-grid">
                <div class="rule-info-card">
                    <h3>Search Information</h3>
        <table>
            <tr><td><strong>Search Outcome:</strong></td><td>{search_outcome}</td></tr>
            <tr><td><strong>Filter Complexity:</strong></td><td>{complexity}</td></tr>
            <tr><td><strong>Data Sources:</strong></td><td>{data_sources}</td></tr>
            <tr><td><strong>Event Types:</strong></td><td>{event_types}</td></tr>
        </table>
                </div>
                <div class="rule-info-card">
                    <h3>Key Indicators</h3>
                    {key_indicators_html}
                </div>
            </div>
        
        <h3>Search Filter</h3>
        <div class="code-block">{search_filter}</div>
    </div>

    <div class="section">
        <h2>Triage Procedure</h2>
        
        <h3>Initial Assessment (5 minutes)</h3>
            <ol class="step-list">
            <li><strong>Verify Alert Context</strong>
                <ul>
                    <li>Check the alert timestamp and frequency</li>
                    <li>Review the affected systems/users</li>
                    <li>Identify the scope of the incident</li>
                </ul>
            </li>
            <li><strong>Check for False Positives</strong>
                <ul>
                    <li>Verify if this is a known legitimate activity</li>
                    <li>Check if affected systems/users are authorized</li>
                    <li>Review recent changes or maintenance activities</li>
                </ul>
            </li>
            <li><strong>Assess Impact</strong>
                <ul>
                    <li>Determine the number of affected systems</li>
                    <li>Identify critical systems or data at risk</li>
                    <li>Evaluate potential business impact</li>
                </ul>
            </li>
        </ol>

        <h3>Investigation Steps (15-30 minutes)</h3>
            <ol class="step-list">
            <li><strong>Gather Additional Context</strong>
                <ul>
                    <li>Review system logs for related events</li>
                    <li>Check for similar patterns in recent history</li>
                    <li>Identify any related security events</li>
                </ul>
            </li>
            <li><strong>Analyze Technical Details</strong>
                <ul>
                    <li>Review the search filter logic</li>
                    <li>Check for any exclusions or exceptions</li>
                    <li>Verify the data sources and event types</li>
                </ul>
            </li>
            <li><strong>Identify Root Cause</strong>
                <ul>
                    <li>Determine what triggered the alert</li>
                    <li>Identify any underlying vulnerabilities</li>
                    <li>Check for any configuration issues</li>
                </ul>
            </li>
        </ol>
    </div>

        <div class="escalation-criteria">
            <h2>Escalation Criteria</h2>
        
            <div class="alert">
                <h3>Immediate Escalation (within 5 minutes) if:</h3>
                <ul>
                    <li>Multiple systems affected</li>
                    <li>Critical systems involved</li>
                    <li>Evidence of data exfiltration</li>
                    <li>Suspicious user activity patterns</li>
                    <li>Known attack patterns detected</li>
                </ul>
        </div>

        <div class="warning">
                <h3>Escalate to Senior Analyst if:</h3>
                <ul>
                    <li>Complex investigation required</li>
                    <li>Multiple data sources involved</li>
                    <li>Need for additional tools or access</li>
                    <li>Potential false positive but uncertain</li>
                </ul>
        </div>
    </div>

        <div class="response-actions">
            <h2>Response Actions</h2>
            <ul>
                <li>Document all findings and actions taken</li>
                <li>Update incident ticket with progress</li>
                <li>Communicate with stakeholders as needed</li>
                <li>Follow up on any remediation actions</li>
        </ul>
    </div>

        <div class="contact-info">
            <h3>Contact Information</h3>
            <p><strong>Author:</strong> {author}</p>
            <p><strong>Contact:</strong> {contact_email}</p>
            <p><strong>Generated:</strong> {generated_date}</p>
            <p><strong>Version:</strong> {version}</p>
        </div>
    </div>
</body>
</html>"""

    @staticmethod
    def get_json_template() -> str:
        """Get JSON template for structured SOP data"""
        return """{{
    "sop_id": "{rule_id}",
    "rule_name": "{rule_name}",
    "category": "{category}",
    "priority": "{priority}",
    "status": "{status}",
    "metadata": {{
        "created_on": "{created_on}",
        "last_updated_on": "{last_updated_on}",
        "generated_date": "{generated_date}",
        "version": "{version}",
        "author": "{author}",
        "contact_email": "{contact_email}"
    }},
    "technical_details": {{
        "description": "{description}",
        "search_outcome": "{search_outcome}",
        "search_filter": "{search_filter}",
        "complexity": "{complexity}",
        "data_sources": "{data_sources}",
        "event_types": "{event_types}"
    }},
    "mitre_attack": {attack_mapping_json},
    "procedures": {{
        "initial_assessment": [
            "Verify Alert Context",
            "Check for False Positives", 
            "Assess Impact"
        ],
        "investigation_steps": [
            "Gather Additional Context",
            "Analyze Technical Details",
            "Identify Root Cause"
        ],
        "escalation_criteria": {{
            "immediate": [
                "Multiple systems affected",
                "Critical systems involved",
                "Evidence of data exfiltration",
                "Suspicious user activity patterns",
                "Known attack patterns detected"
            ],
            "senior_analyst": [
                "Complex investigation required",
                "Multiple data sources involved",
                "Need for additional tools or access",
                "Potential false positive but uncertain"
            ]
        }}
    }},
    "indicators": {{
        "key_indicators": {key_indicators_json},
        "false_positive_indicators": {false_positive_indicators_json}
    }},
    "response_actions": {{
        "immediate": [
            "Document the Alert",
            "Assess Severity",
            "Initial Containment"
        ],
        "short_term": [
            "Gather Evidence",
            "Notify Stakeholders", 
            "Begin Investigation"
        ],
        "long_term": [
            "Complete Investigation",
            "Implement Remediation",
            "Document Lessons Learned"
        ]
    }}
}}"""

    @staticmethod
    def get_pdf_template() -> str:
        """Get PDF-ready template with proper formatting"""
        return """# {rule_name} Standard Operating Procedure

**Document Control**
- **Generated:** {generated_date}
- **Version:** {version}
- **Author:** {author}
- **Contact:** {contact_email}
- **Last Reviewed:** {last_reviewed}

---

## Executive Summary

**Rule ID:** {rule_id}  
**Priority:** {priority}  
**Category:** {category}  
**Status:** {status}

This Standard Operating Procedure (SOP) provides step-by-step guidance for responding to alerts generated by the {rule_name} correlation rule.

---

## Rule Information

| Field | Value |
|-------|-------|
| Rule ID | {rule_id} |
| Rule Name | {rule_name} |
| Status | {status} |
| Priority | {priority} |
| Category | {category} |
| Created | {created_on} |
| Last Updated | {last_updated_on} |

---

## MITRE ATT&CK Mapping

{attack_mapping}

---

## Description

{description}

---

## Technical Details

**Search Outcome:** {search_outcome}  
**Filter Complexity:** {complexity}  
**Data Sources:** {data_sources}  
**Event Types:** {event_types}

### Search Filter
```
{search_filter}
```

---

## Triage Procedure

### Phase 1: Initial Assessment (0-5 minutes)

**Objective:** Quickly assess the alert and determine immediate response requirements.

**Steps:**
1. **Verify Alert Context**
   - Check alert timestamp and frequency
   - Review affected systems/users
   - Identify incident scope

2. **Check for False Positives**
   - Verify known legitimate activity
   - Check authorized systems/users
   - Review recent changes/maintenance

3. **Assess Impact**
   - Count affected systems
   - Identify critical systems/data
   - Evaluate business impact

### Phase 2: Investigation (5-30 minutes)

**Objective:** Gather comprehensive information and determine root cause.

**Steps:**
1. **Gather Additional Context**
   - Review system logs for related events
   - Check similar patterns in recent history
   - Identify related security events

2. **Analyze Technical Details**
   - Review search filter logic
   - Check exclusions/exceptions
   - Verify data sources and event types

3. **Identify Root Cause**
   - Determine alert trigger
   - Identify underlying vulnerabilities
   - Check configuration issues

### Phase 3: Response (30+ minutes)

**Objective:** Implement appropriate response actions and document findings.

**Steps:**
1. **Implement Containment**
   - Isolate affected systems if necessary
   - Block suspicious network traffic
   - Disable compromised accounts

2. **Execute Remediation**
   - Fix identified vulnerabilities
   - Update security controls
   - Improve monitoring

3. **Document and Learn**
   - Complete incident documentation
   - Update procedures
   - Share lessons learned

---

## Escalation Matrix

### Immediate Escalation (within 5 minutes)
- Multiple systems affected
- Critical systems involved
- Evidence of data exfiltration
- Suspicious user activity patterns
- Known attack patterns detected

### Escalate to Senior Analyst
- Complex investigation required
- Multiple data sources involved
- Need for additional tools/access
- Potential false positive but uncertain

---

## Key Indicators

{key_indicators}

---

## False Positive Indicators

{false_positive_indicators}

---

## Response Actions

### Immediate Actions (0-5 minutes)
1. **Document the Alert**
   - Record alert timestamp and details
   - Note affected systems/users
   - Capture initial observations

2. **Assess Severity**
   - Determine if critical incident
   - Check for immediate threats
   - Evaluate potential impact

3. **Initial Containment**
   - Isolate affected systems if necessary
   - Block suspicious network traffic
   - Disable compromised accounts

### Short-term Actions (5-30 minutes)
1. **Gather Evidence**
   - Collect relevant logs and data
   - Document system state
   - Preserve any artifacts

2. **Notify Stakeholders**
   - Alert relevant teams
   - Contact system owners
   - Notify management if critical

3. **Begin Investigation**
   - Start detailed analysis
   - Review related events
   - Identify attack patterns

### Long-term Actions (30+ minutes)
1. **Complete Investigation**
   - Full technical analysis
   - Root cause determination
   - Impact assessment

2. **Implement Remediation**
   - Fix vulnerabilities
   - Update security controls
   - Improve monitoring

3. **Document Lessons Learned**
   - Update procedures
   - Share knowledge
   - Improve response capabilities

---

## References

- MITRE ATT&CK Framework
- Security Platform Documentation
- Internal Security Policies
- Related SOPs and Playbooks

---

**Document End**

Generated: {generated_date}  
Version: {version}  
Author: {author}  
Contact: {contact_email}"""

    @staticmethod
    def get_template_by_category(category: str) -> str:
        """Get appropriate template based on rule category"""
        category_templates = {
            'service_account_misuse': SOPTemplates.get_service_account_template,
            'privilege_escalation': SOPTemplates.get_privilege_escalation_template,
            'configuration_change': SOPTemplates.get_configuration_change_template,
            'data_exfiltration': SOPTemplates.get_data_exfiltration_template,
            'network_anomaly': SOPTemplates.get_network_anomaly_template,
        }
        
        return category_templates.get(category.lower(), SOPTemplates.get_default_template)() 